# Example configuration - copy to wrangler.toml and fill in your values
name = "expense-tracker"
main = "src/worker.js"
compatibility_date = "2023-12-18"

[vars]
APP_URL = "YOUR_APP_URL"
PUBLIC_URL = "YOUR_PUBLIC_URL"
QSTASH_SIGNING_KEY = "YOUR_QSTASH_SIGNING_KEY"
CRON_SECRET = "YOUR_CRON_SECRET"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"
GOOGLE_REDIRECT_URI = "YOUR_GOOGLE_REDIRECT_URI"
R2_ACCESS_KEY_ID = "YOUR_R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "YOUR_R2_SECRET_ACCESS_KEY"
R2_ENDPOINT_URL = "YOUR_R2_ENDPOINT_URL"

[[d1_databases]]
binding = "DB"
database_name = "expenses"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "expenses" 