INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/4/25',
    '1/5/25',
    'DEL FRISCOS GRIL BRNTWOD',
    '',
    'Food & Drink',
    'Sale',
    -78.36,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-04_DEL_FRISCOS_GRIL_BRNTWOD_78.36.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/4/25',
    '1/5/25',
    'DEL FRISCOS GRIL BRNTWOD',
    '',
    'Food & Drink',
    'Sale',
    -65.88,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-04_DEL_FRISCOS_GRIL_BRNTWOD_65.88.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/5/25',
    '1/6/25',
    'THE GOAT MOUNT JULIET',
    '',
    'Food & Drink',
    'Sale',
    -155.6,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-05_THE_GOAT_MOUNT_JULIET_155.6.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/6/25',
    '1/7/25',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -18.47,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-06_METROPOLIS_PARKING_18.47.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/6/25',
    '1/7/25',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-06_METROPOLIS_PARKING_15.99.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/6/25',
    '1/7/25',
    'THE DONELSON PUB',
    '',
    'Food & Drink',
    'Sale',
    -13.5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-06_THE_DONELSON_PUB_13.5.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/8/25',
    '1/9/25',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -17.88,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-08_METROPOLIS_PARKING_17.88.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/8/25',
    '1/9/25',
    'CALENDARBRIDGE',
    '',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '1/9/25',
    '1/9/25',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2025-01-09_METROPOLIS_PARKING_21.0.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/11/24',
    '10/13/24',
    'SH NASHVILLE - OTHER',
    'Drinks with Drew Bennett - Eric Church',
    'Travel',
    'Sale',
    -62.04,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-11_SH_NASHVILLE_-_OTHER_62.04.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/11/24',
    '10/13/24',
    'SH NASHVILLE - OTHER',
    'Bobbii Jacobs',
    'Travel',
    'Sale',
    -27.14,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-11_SH_NASHVILLE_-_OTHER_27.14.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/14/24',
    '10/15/24',
    'CLOUDFLARE',
    'Downhome.com server',
    'Shopping',
    'Sale',
    -5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-14_CLOUDFLARE_5.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/15/24',
    '10/17/24',
    'CHAR GREEN HILLS',
    'Bill Stapleton, Scott Siman, Kelly Clague, Brian Kaplan',
    'Food & Drink',
    'Sale',
    -422.72,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-15_CHAR_GREEN_HILLS_422.72.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/18/24',
    'CORNER PUB',
    'Kevin Sabbe and Arlis Albritton - songwriter',
    'Food & Drink',
    'Sale',
    -133.44,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_CORNER_PUB_133.44.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/18/24',
    'SH NASHVILLE - OTHER',
    'Lunch with Andrew Cohen',
    'Travel',
    'Sale',
    -37.48,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_SH_NASHVILLE_-_OTHER_37.48.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/18/24',
    'SH NASHVILLE - OTHER',
    'Dawn Gates - UMG',
    'Travel',
    'Sale',
    -29.73,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_SH_NASHVILLE_-_OTHER_29.73.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/17/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_PMC_-_PAID_PARKING_26.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/17/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_PMC_-_PAID_PARKING_26.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/16/24',
    '10/17/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -19.94,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-16_PMC_-_PAID_PARKING_19.94.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/18/24',
    '10/20/24',
    'CHARTMETRIC',
    'Analytics and Industry Metrics',
    'Shopping',
    'Sale',
    -160,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-18_CHARTMETRIC_160.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/22/24',
    '10/22/24',
    'RUNWAY STANDARD PLAN',
    'Video and Graphics for Presentation',
    'Shopping',
    'Sale',
    -144,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-22_RUNWAY_STANDARD_PLAN_144.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/23/24',
    '10/25/24',
    '201 BELCOURT LOT',
    'Parking',
    'Travel',
    'Sale',
    -6.73,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-23_201_BELCOURT_LOT_6.73.jpg',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/25/24',
    '10/27/24',
    'BONHOMME PLACE GARAGE',
    'St Louis Parking - Jackie Joyner',
    'Travel',
    'Sale',
    -27,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-25_BONHOMME_PLACE_GARAGE_27.0.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/26/24',
    '10/27/24',
    'IMDbPro',
    'IMDB Pro Monthly',
    'Bills & Utilities',
    'Sale',
    -19.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-26_IMDbPro_19.99.png',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/28/24',
    '10/30/24',
    'JJK FOUNDATION',
    'Jackie Joyner-Kersee Event',
    'Gifts & Donations',
    'Sale',
    -60,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-28_JJK_FOUNDATION_60.0.png',
    'Conference',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/3/24',
    '10/4/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -20.76,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-03_PMC_-_PAID_PARKING_20.76.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/4/24',
    '10/6/24',
    'SH NASHVILLE - OTHER',
    'Meeting with Terry Cologne - Merch',
    'Travel',
    'Sale',
    -23.27,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-04_SH_NASHVILLE_-_OTHER_23.27.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/4/24',
    '10/6/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-04_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/7/24',
    '10/9/24',
    'SH NASHVILLE - OTHER',
    'Sloan Cavitt WME',
    'Travel',
    'Sale',
    -52.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-07_SH_NASHVILLE_-_OTHER_52.99.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/7/24',
    '10/9/24',
    'SH NASHVILLE - OTHER',
    'Kelly Clague Catch Up',
    'Travel',
    'Sale',
    -29.73,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-07_SH_NASHVILLE_-_OTHER_29.73.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/8/24',
    '10/10/24',
    'CORNER PUB',
    'Alex Sera - WME',
    'Food & Drink',
    'Sale',
    -83.92,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-08_CORNER_PUB_83.92.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/8/24',
    '10/8/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-08_METROPOLIS_PARKING_26.25.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/8/24',
    '10/9/24',
    'CALENDARBRIDGE',
    'Calendar Sync',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '10/9/24',
    '10/10/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -30.05,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-10-09_PMC_-_PAID_PARKING_30.05.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/1/24',
    '11/3/24',
    'SH NASHVILLE - OTHER',
    'TIm Foisset - Spotify',
    'Travel',
    'Sale',
    -23.27,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-01_SH_NASHVILLE_-_OTHER_23.27.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/1/24',
    '11/3/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-01_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/12/24',
    '11/14/24',
    'SH NASHVILLE - OTHER',
    'Scott, Tim, Bill, Brian - CAA Recap',
    'Travel',
    'Sale',
    -176.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-12_SH_NASHVILLE_-_OTHER_176.99.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/13/24',
    '11/13/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-13_METROPOLIS_PARKING_15.99.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/14/24',
    '11/15/24',
    'ANTHROPIC',
    'Claude Monthly',
    'Shopping',
    'Sale',
    -27.44,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-14_ANTHROPIC_27.44.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/14/24',
    '11/15/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-14_METROPOLIS_PARKING_15.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/14/24',
    '11/17/24',
    'SH NASHVILLE - OTHER',
    'Jay - Apple Music',
    'Travel',
    'Sale',
    -7.76,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-14_SH_NASHVILLE_-_OTHER_7.76.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/14/24',
    '11/15/24',
    'CLOUDFLARE',
    'DownHome.com - Hosting',
    'Shopping',
    'Sale',
    -5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-14_CLOUDFLARE_5.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/15/24',
    '11/17/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -29.4,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-15_METROPOLIS_PARKING_29.4.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/15/24',
    '11/17/24',
    'SH NASHVILLE - OTHER',
    'Michelle De Leon - Coffee',
    'Travel',
    'Sale',
    -16.8,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-15_SH_NASHVILLE_-_OTHER_16.8.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/15/24',
    '11/15/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-15_METROPOLIS_PARKING_15.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/16/24',
    '11/17/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-16_METROPOLIS_PARKING_26.25.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/17/24',
    '11/19/24',
    'BROADWAY BREWHOUSE DOWNTO',
    'Rae - showrunner ten year town, Kevin Sabbe, Andrew cohen',
    'Food & Drink',
    'Sale',
    -47.34,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-17_BROADWAY_BREWHOUSE_DOWNTO_47.34.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/18/24',
    '11/19/24',
    'CHARTMETRIC',
    'Analytics and Industry Metrics',
    'Shopping',
    'Sale',
    -160,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-18_CHARTMETRIC_160.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/19/24',
    '11/21/24',
    'Marsh House',
    'CMA Awards',
    'Food & Drink',
    'Sale',
    -30.69,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-19_Marsh_House_30.69.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/20/24',
    '11/20/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -20.66,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-20_METROPOLIS_PARKING_20.66.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/21/24',
    '11/22/24',
    'PARKING OMNI NASHVILLE PA',
    'Parking CMA Awards',
    'Travel',
    'Sale',
    -34.96,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-21_PARKING_OMNI_NASHVILLE_PA_34.96.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    0.9
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/21/24',
    '11/22/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-21_METROPOLIS_PARKING_26.25.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/23/24',
    '11/24/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-23_METROPOLIS_PARKING_26.25.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/25/24',
    '11/25/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-25_METROPOLIS_PARKING_26.25.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/4/24',
    '11/6/24',
    'CORNER PUB',
    'Scott Siman and Brian',
    'Food & Drink',
    'Sale',
    -39.87,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-04_CORNER_PUB_39.87.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/6/24',
    '11/7/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -23.21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-06_PMC_-_PAID_PARKING_23.21.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/7/24',
    '11/7/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-07_METROPOLIS_PARKING_26.25.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/8/24',
    '11/10/24',
    'SH NASHVILLE - OTHER',
    'Kevin Sabbe, Brian Kaplan',
    'Travel',
    'Sale',
    -45.24,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-08_SH_NASHVILLE_-_OTHER_45.24.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/8/24',
    '11/10/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -10.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-08_METROPOLIS_PARKING_10.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '11/8/24',
    '11/10/24',
    'CALENDARBRIDGE',
    'Calendar Sync',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-11-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/12/24',
    '12/13/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-12_METROPOLIS_PARKING_21.0.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/17/24',
    '12/17/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-17_METROPOLIS_PARKING_21.0.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/18/24',
    '12/19/24',
    'CHARTMETRIC',
    'Analytics and Industry Metrics',
    'Shopping',
    'Sale',
    -160,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-18_CHARTMETRIC_160.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/18/24',
    '12/19/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-18_METROPOLIS_PARKING_15.99.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/19/24',
    '12/19/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -16.29,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-19_METROPOLIS_PARKING_16.29.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/2/24',
    '12/3/24',
    'THE URBAN JUICER',
    '',
    'Food & Drink',
    'Sale',
    -12.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-02_THE_URBAN_JUICER_12.25.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/6/24',
    '12/8/24',
    'COSMOPOL-BANG BAR',
    '',
    'Food & Drink',
    'Sale',
    -33.38,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-06_COSMOPOL-BANG_BAR_33.38.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/6/24',
    '12/8/24',
    'CURB LV TAXI YCS',
    '',
    'Travel',
    'Sale',
    -18.89,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-06_CURB_LV_TAXI_YCS_18.89.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/7/24',
    '12/9/24',
    'PIZZA FORTE HARD ROCK',
    '',
    'Food & Drink',
    'Sale',
    -33.16,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-07_PIZZA_FORTE_HARD_ROCK_33.16.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/7/24',
    '12/9/24',
    'DESERT STAR LOUNGE',
    '',
    'Food & Drink',
    'Sale',
    -19,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-07_DESERT_STAR_LOUNGE_19.0.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/8/24',
    '12/10/24',
    'VHLV-KITCHEN AT COMMON',
    '',
    'Food & Drink',
    'Sale',
    -35,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-08_VHLV-KITCHEN_AT_COMMON_35.0.jpg',
    'Uncategorized',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '12/8/24',
    '12/9/24',
    'CALENDARBRIDGE',
    '',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-12-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/12/24',
    '7/14/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -9.29,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-12_PMC_-_PAID_PARKING_9.29.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/12/24',
    '7/14/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -9.29,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-12_PMC_-_PAID_PARKING_9.29.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/14/24',
    '7/15/24',
    'CLOUDFLARE',
    'Hosting',
    'Shopping',
    'Sale',
    -5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-14_CLOUDFLARE_5.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/17/24',
    '7/18/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -11.32,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-17_METROPOLIS_PARKING_11.32.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/17/24',
    '7/18/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -7.55,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-17_METROPOLIS_PARKING_7.55.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/17/24',
    '7/18/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -4.49,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-17_METROPOLIS_PARKING_4.49.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/19/24',
    '7/21/24',
    'AUDREY - SEAN BROCK GROU',
    'Project Betty - Dinner in Nashville with Agency, Jason, Brian, Tom, Tyler 4 from team JPG',
    'Food & Drink',
    'Sale',
    -1487.8,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-19_AUDREY_-_SEAN_BROCK_GROU_1487.8.pdf',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/25/24',
    '7/26/24',
    'ROSTR PRO',
    'Industry Contacts System',
    'Shopping',
    'Sale',
    -50,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-25_ROSTR_PRO_50.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/25/24',
    '7/28/24',
    'CHAR GREEN HILLS',
    'Lunch with State - Governor Team',
    'Food & Drink',
    'Sale',
    -43.6,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-25_CHAR_GREEN_HILLS_43.6.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/25/24',
    '7/26/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -9.29,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-25_PMC_-_PAID_PARKING_9.29.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/26/24',
    '7/26/24',
    'IMDbPro',
    'Contacts App',
    'Bills & Utilities',
    'Sale',
    -19.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-26_IMDbPro_19.99.png',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/26/24',
    '7/28/24',
    'SH NASHVILLE - OTHER',
    'Job Interview - Assistant',
    'Travel',
    'Sale',
    -9.05,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-26_SH_NASHVILLE_-_OTHER_9.05.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/28/24',
    '7/29/24',
    'CARTA NORTH GARAGE',
    'Parking',
    'Travel',
    'Sale',
    -11,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-28_CARTA_NORTH_GARAGE_11.0.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/30/24',
    '8/1/24',
    'SH NASHVILLE - OTHER',
    'Jason and Jules Wortman - Artist Manager',
    'Travel',
    'Sale',
    -24.91,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-30_SH_NASHVILLE_-_OTHER_24.91.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '7/30/24',
    '7/31/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-07-30_METROPOLIS_PARKING_15.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/1/24',
    '8/2/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -15.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-01_METROPOLIS_PARKING_15.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/13/24',
    '8/15/24',
    'OPTIMIST NASHVILLE',
    'Team Dinner Nashville - Alix, Anne Marie, Brian, Doug Phillips, Jason, Luanne',
    'Food & Drink',
    'Sale',
    -896.44,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-13_OPTIMIST_NASHVILLE_896.44.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/13/24',
    '8/14/24',
    'O-KU NASHVILLE',
    'Team Meeting Drinks Nashville - Alix, Anne Marie, Brian -',
    'Food & Drink',
    'Sale',
    -58.21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-13_O-KU_NASHVILLE_58.21.jpg',
    'Company Meetings and Meals',
    'business',
    0.85
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/13/24',
    '8/15/24',
    'OPTIMIST NASHVILLE',
    'Team Dinner Nashville - Alix, Anne Marie, Brian, Doug Phillips, Jason, Luanne',
    'Food & Drink',
    'Sale',
    -44.32,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-13_OPTIMIST_NASHVILLE_44.32.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/14/24',
    '8/25/24',
    'SH NASHVILLE - OTHER',
    'Sheryl Longin - Meeting',
    'Travel',
    'Sale',
    -27.14,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-14_SH_NASHVILLE_-_OTHER_27.14.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/14/24',
    '8/16/24',
    'MAFIAOZAS',
    'Kelly Scott Tim Staples Brian meetings',
    'Food & Drink',
    'Sale',
    -15.38,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-14_MAFIAOZAS_15.38.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/14/24',
    '8/14/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -10.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-14_METROPOLIS_PARKING_10.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/14/24',
    '8/15/24',
    'CLOUDFLARE',
    'Monthly Hosting',
    'Shopping',
    'Sale',
    -5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-14_CLOUDFLARE_5.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/15/24',
    '8/18/24',
    'SH NASHVILLE - OTHER',
    'Sandy Howard - Mcgraw Sister - Lunch',
    'Travel',
    'Sale',
    -74.97,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-15_SH_NASHVILLE_-_OTHER_74.97.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/17/24',
    '8/18/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -42,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-17_METROPOLIS_PARKING_42.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/18/24',
    '8/19/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -31.5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-18_METROPOLIS_PARKING_31.5.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/19/24',
    '8/22/24',
    'SH NASHVILLE - OTHER',
    'Joel, Chandra, Paul, Pitch Outsiders',
    'Travel',
    'Sale',
    -51.7,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-19_SH_NASHVILLE_-_OTHER_51.7.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/19/24',
    '8/22/24',
    'SH NASHVILLE - OTHER',
    'Lunch with Rachel - Spotify',
    'Travel',
    'Sale',
    -47.82,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-19_SH_NASHVILLE_-_OTHER_47.82.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/19/24',
    '8/22/24',
    'SH NASHVILLE - OTHER',
    'Sam Parker - Beach Boys Pitch',
    'Travel',
    'Sale',
    -31.02,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-19_SH_NASHVILLE_-_OTHER_31.02.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/20/24',
    '8/20/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -27.42,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-20_METROPOLIS_PARKING_27.42.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/20/24',
    '8/21/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -23.21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-20_PMC_-_PAID_PARKING_23.21.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/21/24',
    '8/22/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -38.03,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-21_PMC_-_PAID_PARKING_38.03.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/22/24',
    '8/23/24',
    'LinkedIn JOB 9849229796',
    'LinkedIn Job Post - Assistant',
    'Bills & Utilities',
    'Sale',
    -174.56,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-22_LinkedIn_JOB_9849229796_174.56.png',
    'BD: Advertising & Promotion',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/22/24',
    '8/22/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -29.28,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-22_PMC_-_PAID_PARKING_29.28.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/22/24',
    '8/22/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -22.51,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-22_PMC_-_PAID_PARKING_22.51.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/23/24',
    '8/25/24',
    'CORNER PUB',
    'Jason Maynard - Oracle - Brian',
    'Food & Drink',
    'Sale',
    -79.64,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-23_CORNER_PUB_79.64.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/23/24',
    '8/25/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -10.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-23_METROPOLIS_PARKING_10.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/23/24',
    '8/25/24',
    'SH NASHVILLE - OTHER',
    'Interview Candidate for assistant',
    'Travel',
    'Sale',
    -9.05,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-23_SH_NASHVILLE_-_OTHER_9.05.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/25/24',
    '8/26/24',
    'ROSTR PRO',
    'Industry Contacts System',
    'Shopping',
    'Sale',
    -50,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-25_ROSTR_PRO_50.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/26/24',
    '8/27/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -23.21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-26_PMC_-_PAID_PARKING_23.21.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/26/24',
    '8/26/24',
    'IMDbPro',
    'IMBD Monthly',
    'Bills & Utilities',
    'Sale',
    -19.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-26_IMDbPro_19.99.png',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/28/24',
    '8/29/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-28_PMC_-_PAID_PARKING_26.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/28/24',
    '8/30/24',
    'SH NASHVILLE - OTHER',
    'Patrick Humes',
    'Travel',
    'Sale',
    -18.1,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-28_SH_NASHVILLE_-_OTHER_18.1.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/29/24',
    '9/1/24',
    'CHAR GREEN HILLS',
    'Todd Cassetty - Nashville Manager and Songwriter / Event Owner',
    'Food & Drink',
    'Sale',
    -67.81,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-29_CHAR_GREEN_HILLS_67.81.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/29/24',
    '8/30/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -9.29,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-29_PMC_-_PAID_PARKING_9.29.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/30/24',
    '8/30/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -16.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-30_METROPOLIS_PARKING_16.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/5/24',
    '8/7/24',
    'SH NASHVILLE - OTHER',
    'Paul Zamek, Brian, Sam Parker Pitch',
    'Travel',
    'Sale',
    -58.16,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-05_SH_NASHVILLE_-_OTHER_58.16.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/5/24',
    '8/7/24',
    'SH NASHVILLE - OTHER',
    'Charly Salvatore - Artist Manager Meeting',
    'Travel',
    'Sale',
    -38.78,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-05_SH_NASHVILLE_-_OTHER_38.78.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/5/24',
    '8/6/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-05_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/5/24',
    '8/7/24',
    'SH NASHVILLE - OTHER',
    'Chandra Laplume - Producer Meeting',
    'Travel',
    'Sale',
    -9.05,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-05_SH_NASHVILLE_-_OTHER_9.05.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/6/24',
    '8/6/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-06_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/6/24',
    '8/7/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-06_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/6/24',
    '8/8/24',
    'SH NASHVILLE - OTHER',
    'Kelly Clague and Brian Kaplan',
    'Travel',
    'Sale',
    -18.1,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-06_SH_NASHVILLE_-_OTHER_18.1.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/8/24',
    '8/9/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -38.03,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-08_PMC_-_PAID_PARKING_38.03.png',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '8/8/24',
    '8/9/24',
    'CALENDARBRIDGE',
    'Calendar Bridge',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-08-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/10/24',
    '9/11/24',
    'DEL FRISCOS GRILL NASHVL',
    'Len Davi - Headphone developer (Beats by Dre)',
    'Food & Drink',
    'Sale',
    -69.9,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-10_DEL_FRISCOS_GRILL_NASHVL_69.9.png',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/11/24',
    '9/12/24',
    'CADILLAC BAR LAS VEGAS',
    'Tim Staples, Jason Ross, Brian Kaplan, Matt Weaver, Joel Bergvall - Area 15',
    'Food & Drink',
    'Sale',
    -86.62,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-11_CADILLAC_BAR_LAS_VEGAS_86.62.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    0.85
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/12/24',
    '9/13/24',
    'GNLV THE GRILLE',
    'Vegas - Travel',
    'Food & Drink',
    'Sale',
    -27.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-12_GNLV_THE_GRILLE_27.22.jpg',
    'DH: Travel costs - Meals',
    'business',
    0.8
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/13/24',
    '9/15/24',
    'GOLDEN NUGGET HOTEL LV',
    'Las Vegas Area 15 Hotel',
    'Travel',
    'Sale',
    -313.01,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-13_GOLDEN_NUGGET_HOTEL_LV_313.01.png',
    'Travel Costs - Hotel',
    'business',
    0.95
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/14/24',
    '9/15/24',
    'CLOUDFLARE',
    'downhome.com server',
    'Shopping',
    'Sale',
    -5,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-14_CLOUDFLARE_5.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/16/24',
    '9/18/24',
    'SH NASHVILLE - OTHER',
    'Joel, Chandra Laplume, Outsiders Pitch',
    'Travel',
    'Sale',
    -40.07,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-16_SH_NASHVILLE_-_OTHER_40.07.jpg',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/16/24',
    '9/17/24',
    'PARKINGMANAGEMENTCOMPANY',
    'Parking',
    'Travel',
    'Sale',
    -38.24,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-16_PARKINGMANAGEMENTCOMPANY_38.24.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    0.9
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/16/24',
    '9/17/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-16_PMC_-_PAID_PARKING_26.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/16/24',
    '9/17/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -17.88,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-16_METROPOLIS_PARKING_17.88.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/18/24',
    '9/22/24',
    'SH NASHVILLE - OTHER',
    'Randy Bernard and Patrick Humes',
    'Travel',
    'Sale',
    -71.09,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-18_SH_NASHVILLE_-_OTHER_71.09.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/18/24',
    '9/19/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -29.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-18_PMC_-_PAID_PARKING_29.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/18/24',
    '9/18/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -10.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-18_METROPOLIS_PARKING_10.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/19/24',
    '9/22/24',
    'SH NASHVILLE - OTHER',
    'Dan Rowe - Firebird',
    'Travel',
    'Sale',
    -38.78,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-19_SH_NASHVILLE_-_OTHER_38.78.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/19/24',
    '9/22/24',
    'SH NASHVILLE - OTHER',
    'Live in the Winery - Bobbi Jacobs',
    'Travel',
    'Sale',
    -11.63,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-19_SH_NASHVILLE_-_OTHER_11.63.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/20/24',
    '9/20/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-20_METROPOLIS_PARKING_26.25.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/21/24',
    '9/23/24',
    '201 BELCOURT LOT',
    'Parking',
    'Travel',
    'Sale',
    -5.6,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-21_201_BELCOURT_LOT_5.6.jpg',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/24/24',
    '9/26/24',
    'SH NASHVILLE - OTHER',
    'Bill, Brian, Scott, Tim, Tyler, Tom, Patrick, Jason',
    'Travel',
    'Sale',
    -689.59,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-24_SH_NASHVILLE_-_OTHER_689.59.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/25/24',
    '9/27/24',
    'SH NASHVILLE - OTHER',
    'Bill Stapleton, Tim Staples, Jason Ross, Tyler Stevens, Tom May, Scott Siman',
    'Travel',
    'Sale',
    -224.64,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-25_SH_NASHVILLE_-_OTHER_224.64.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/25/24',
    '9/26/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-25_PMC_-_PAID_PARKING_26.22.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/25/24',
    '9/26/24',
    'LAZGO NASHVILLE M32180',
    'Parking',
    'Travel',
    'Sale',
    -5.18,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-25_LAZGO_NASHVILLE_M32180_5.18.pdf',
    'DH: Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/26/24',
    '9/26/24',
    'IMDbPro',
    'IMDB Pro Monthly',
    'Bills & Utilities',
    'Sale',
    -19.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-26_IMDbPro_19.99.png',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/26/24',
    '9/29/24',
    'SH NASHVILLE - OTHER',
    'Andrew Cohen / Brian Kaplan Catch up',
    'Travel',
    'Sale',
    -14.22,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-26_SH_NASHVILLE_-_OTHER_14.22.png',
    'Company Meetings and Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/3/24',
    '9/4/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -17.88,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-03_METROPOLIS_PARKING_17.88.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/4/24',
    '9/6/24',
    'CORNER PUB',
    'Jason Maynard Oracle',
    'Food & Drink',
    'Sale',
    -45.15,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-04_CORNER_PUB_45.15.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/4/24',
    '9/6/24',
    'CORNER PUB',
    'Jason Maynard Oracle',
    'Food & Drink',
    'Sale',
    -39.78,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-04_CORNER_PUB_39.78.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/4/24',
    '9/5/24',
    'PMC - PAID PARKING',
    'Parking',
    'Travel',
    'Sale',
    -24.59,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-04_PMC_-_PAID_PARKING_24.59.jpg',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/5/24',
    '9/8/24',
    'SH NASHVILLE - OTHER',
    'Lunch with Clay Hunnicut',
    'Travel',
    'Sale',
    -100.82,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-05_SH_NASHVILLE_-_OTHER_100.82.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/5/24',
    '9/6/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -21,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-05_METROPOLIS_PARKING_21.0.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/5/24',
    '9/6/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -10.99,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-05_METROPOLIS_PARKING_10.99.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/6/24',
    '9/8/24',
    'SH NASHVILLE - OTHER',
    'Lunch - Steve Emley',
    'Travel',
    'Sale',
    -40.07,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-06_SH_NASHVILLE_-_OTHER_40.07.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/6/24',
    '9/8/24',
    'SH NASHVILLE - OTHER',
    'Coffee Robert Deaton',
    'Travel',
    'Sale',
    -24.56,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-06_SH_NASHVILLE_-_OTHER_24.56.jpg',
    'DH:  BD:  Client Business Meals',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/7/24',
    '9/8/24',
    'GOLDEN NUGGET HOTEL LV',
    'Las Vegas Travel - Area 15',
    'Travel',
    'Sale',
    -100.57,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-07_GOLDEN_NUGGET_HOTEL_LV_100.57.png',
    'DH: Travel Costs - Hotel',
    'business',
    0.95
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/7/24',
    '9/8/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -26.25,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-07_METROPOLIS_PARKING_26.25.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/8/24',
    '9/9/24',
    'CALENDARBRIDGE',
    'Calendar Sync Software',
    'Shopping',
    'Sale',
    -10,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-08_CALENDARBRIDGE_10.0.pdf',
    'Software subscriptions',
    'business',
    1
  );
INSERT INTO expenses (
    transaction_date,
    post_date,
    merchant,
    description,
    category,
    type,
    amount,
    memo,
    receipt_url,
    expensify_category,
    expense_type,
    categorization_confidence
  ) VALUES (
    '9/9/24',
    '9/10/24',
    'METROPOLIS PARKING',
    'Parking',
    'Travel',
    'Sale',
    -7.55,
    '',
    'https://pub-91e5050716e3427f88fd198e728b5a18.r2.dev/expensify/imported/2024-09-09_METROPOLIS_PARKING_7.55.pdf',
    'Travel Costs - Gas/Rental Car',
    'business',
    1
  );